ExpenseTracker/Models/ErrorViewModel.cs
namespace ExpenseTracker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExpenseTracker/Controllers/CategoryController.cs
using ExpenseTracker.BLL.DTO;
using ExpenseTracker.BLL.Services.API;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ExpenseTracker.Controllers;


[Authorize]
public class CategoryController : Controller
{
    private readonly ICategoryService _categoryService;

    public CategoryController(ICategoryService categoryService)
    {
        _categoryService = categoryService;
    }

    // GET: Category
    public async Task<IActionResult> Index()
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var categories = await _categoryService.GetAllCategoriesAsync(loggedInUserId);
        return View(categories.Data);
    }


    // GET: Category/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Category/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CategoryDto categoryDto)
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var response = await _categoryService.CreateCategoryAsync(categoryDto, loggedInUserId);

        if (response.Success)
        {
            return RedirectToAction("Index");
        }

        ModelState.AddModelError("", string.Join(", ", response.Errors));
        return View(categoryDto);
    }

    // GET: Category/Edit/5
    public async Task<IActionResult> Edit(int id)
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var response = await _categoryService.GetCategoryByIdAsync(id, loggedInUserId);

        if (!response.Success)
        {
            return NotFound();
        }

        return View(response.Data);
    }

    // POST: Category/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(CategoryDto categoryDto)
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var response = await _categoryService.UpdateCategoryAsync(categoryDto, loggedInUserId);

        if (response.Success)
        {
            return RedirectToAction("Index");
        }

        ModelState.AddModelError("", string.Join(", ", response.Errors));
        return View(categoryDto);
    }

    // GET: Category/Delete/5
    public async Task<IActionResult> Delete(int id)
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var response = await _categoryService.GetCategoryByIdAsync(id, loggedInUserId);

        if (!response.Success)
        {
            return NotFound();
        }

        return View(response.Data);
    }

    // POST: Category/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var response = await _categoryService.DeleteCategoryAsync(id, loggedInUserId);

        if (response.Success)
        {
            return RedirectToAction("Index");
        }

        ModelState.AddModelError("", string.Join(", ", response.Errors));
        return View();
    }
}

ExpenseTracker/Controllers/HomeController.cs
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExpenseTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExpenseTracker/Controllers/TransactionController.cs
using ExpenseTracker.BLL.DTO;
using ExpenseTracker.BLL.Services.API;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ExpenseTracker.Controllers;

[Authorize]
public class TransactionController : Controller
{
    private readonly ITransactionsService _transactionsService;
    private readonly ICategoryService _categoryService;
    private readonly IUsersService _usersService;

    public TransactionController(ITransactionsService transactionsService, ICategoryService categoryService, IUsersService usersService)
    {
        _transactionsService = transactionsService;
        _categoryService = categoryService;
        _usersService = usersService;
    }
    // GET: TransactionController
    // GET: Transaction
    public async Task<IActionResult> Index()
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var transactionsResponse = await _transactionsService.GetAllTransactionsAsync(loggedInUserId);
        
        if (transactionsResponse.Success)
        {
            var transactions = transactionsResponse.Data;
            return View(transactions);
        }

        ModelState.AddModelError("", string.Join(", ", transactionsResponse.Errors));
        return View(new List<TransactionDto>());
    }

    // GET: TransactionController/Details/5
    public ActionResult Details(int id)
    {
        return View();
    }

    // GET: TransactionController/Create
    public async Task<IActionResult> Create()
    {
        int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var categories = await _categoryService.GetAllCategoriesAsync(loggedInUserId);
        ViewBag.Categories = categories.Data;

        var transactionDto = new TransactionDto();
        return View(transactionDto);
    }

    // POST: TransactionController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(TransactionDto transactionDto)
    {
        try
        {
            int loggedInUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (ModelState.IsValid)
            {
                transactionDto.UserId = loggedInUserId;

                var response = await _transactionsService.AddTransactionAsync(transactionDto, loggedInUserId);

                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", string.Join(", ", response.Errors));
            }

            var categories = await _categoryService.GetAllCategoriesAsync(loggedInUserId);
            ViewBag.Categories = categories.Data;
            return View(transactionDto);
        }
        catch
        {
            return View();
        }
    }

    


    // GET: TransactionController/Edit/5
    public ActionResult Edit(int id)
    {
        return View();
    }

    // POST: TransactionController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    // GET: TransactionController/Delete/5
    public ActionResult Delete(int id)
    {
        return View();
    }

    // POST: TransactionController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}

ExpenseTracker/Views/Category/Create.cshtml
@model ExpenseTracker.BLL.DTO.CategoryDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CategoryDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/Category/Delete.cshtml
@model ExpenseTracker.BLL.DTO.CategoryDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoryDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExpenseTracker/Views/Category/Edit.cshtml
@model ExpenseTracker.BLL.DTO.CategoryDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CategoryDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/Category/Index.cshtml
@model IEnumerable<ExpenseTracker.BLL.DTO.CategoryDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

ExpenseTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExpenseTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseTracker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExpenseTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transactions</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />  
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ExpenseTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExpenseTracker/Views/Transaction/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@using ExpenseTracker.DAL.Enums;
@model ExpenseTracker.BLL.DTO.TransactionDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TransactionDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="TransactionType" class="control-label"></label>
                <select asp-for="TransactionType" asp-items="Html.GetEnumSelectList<TransactionType>()" class="form-control">
                    <option value="">Select Transaction Type</option>
                </select>
                <span asp-validation-for="TransactionType" class="text-danger"></span>
            </div>

           
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items='new SelectList(ViewBag.Categories, "Id", "Name")' class="form-control">
                    <option value="">Select Category</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/Transaction/Index.cshtml
@model IEnumerable<ExpenseTracker.BLL.DTO.TransactionDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransactionType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>